# Generated by Django 3.1.3 on 2020-11-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201113_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models
                                    .deletion.SET_NULL,
                                    related_name='group',
                                    to='posts.group'),
        ),
    ]
