# Generated by Django 2.2.9 on 2021-01-31 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201127_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=(
                                    django.db.models.deletion.CASCADE),
                                    related_name='posts',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=(
                                        django.db.models.deletion.SET_NULL),
                                    related_name='group', to='posts.Group',
                                    verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
