# Generated by Django 2.2.9 on 2021-02-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210131_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='расскажите,'
                                             ' что происходит'
                                             ' в вашей группе )',
                                   max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Часть '
                                             ' - это как '
                                             'заголовок, но в адресной'
                                             'строке', unique=True,
                                   verbose_name='Введите понятную ва'
                                                'м часть URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Назовите как-то '
                                             'кгруппу', max_length=200,
                                   verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='имя авто'
                                              'ра',
                                    on_delete=(
                                        django.db.models.deletion.CASCADE),
                                    related_name='posts',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    help_text='Название группы',
                                    null=True,
                                    on_delete=(
                                        django.db.models.deletion.SET_NULL),
                                    related_name='group', to='posts.Group',
                                    verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True,
                                       help_text='Дата создания Поста',
                                       verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='основное содержание поста',
                                   verbose_name='Текст'),
        ),
    ]
